version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - sudo apt-get update
      - sudo apt-get install -y maven
      - mvn -version
      - echo "maven installed successfully..."

  pre_build:
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Build started"
      - cd spring-boot-app/
      - mvn clean install
      - ls target
      - echo "Build completed"

  post_build:
    commands:
      - echo "running tests"
      - echo "Building Docker image..."
      - DOCKER_REGISTRY_URL=$(echo "$DOCKER_REGISTRY_URL" | tr -d '\n\r')
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$CLEAN_DOCKER_REGISTRY_USERNAME/sprint_boot_shopping:latest" .
      - docker push "$CLEAN_DOCKER_REGISTRY_USERNAME/sprint_boot_shopping:latest"
      - echo "Build completed successfully!"

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
